### ISSUE TITLE
Shall we add requests to the default packages for nodejs:10?

### ISSUE THREAD

**Issue by jiangpengcheng** [apache/incubator-openwhisk-runtime-nodejs#142]
there are three official actions which use the `request` package in https://github.com/apache/incubator-openwhisk-catalog

- packages/github/webhook.js
- packages/slack/post.js
- packages/weather/forecast.js

but cannot found such package while invoke these actions:

```
    "response": {
        "result": {
            "error": "Initialization has failed due to: Error: Cannot find module 'request'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:508:25)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at eval (eval at evalScript (/nodejsAction/runner.js:180:16), <anonymous>:4:15)\n    at eval (eval at evalScript (/nodejsAction/runner.js:180:16), <anonymous>:175:14)\n    at evalScript (/nodejsAction/runner.js:180:16)\n    at NodeActionRunner.init (/nodejsAction/runner.js:67:35)\n    at doInit (/nodejsAction/src/service.js:166:14)\n    at initCode (/nodejsAction/src/service.js:93:24)"
        },
        "status": "action developer error",
        "success": false
    }
```

**Comment by rabbah** [comment]
use `needle` instead? that should be available in all the node runtimes iirc.

**Comment by jiangpengcheng** [comment]
great, it will be better

**Comment by jiangpengcheng** [comment]
closed as resolved
